### ISSUE TITLE
Convertir Mayusculas

### ISSUE THREAD

**Issue by jchantej** [jchantej/IWVG.SwC.JuanJimenez#2]
Convertir Mayusculas.
[mas información..](../wiki/Descripción-de-Tareas#2-clase-user-método-para-devolver-mayúsculas)

**Comment by angelmart** [comment]
Se ha implementado el método fullNameUpper en la clase User, que devuelve un String con nombre y apellidos en mayúsculas. 
En el test de User se ha añadido un test que compruebe la validez de este método utilizando el ejemplo suministrado en la wiki (JUAN JIMENEZ).
