### ISSUE TITLE
Encontrar Menor

### ISSUE THREAD

**Issue by jchantej** [jchantej/IWVG.SwC.JuanJimenez#3]
Encontrar el Menor
[mas información..](../wiki/Descripción-de-Tareas#2-clase-user-método-para-devolver-mayúsculas)

**Comment by joaquinz916** [comment]
Compañero me parece que el método para sumar los elementos ya estaba realizado, adjunto el link.

https://github.com/jchantej/IWVG.SwC.JuanJimenez/blob/e86a53a22d73c1ddb9c255a876b174c55268eb68/src/main/java/IWVG/SwC/JuanJimenez/DecimalCollection.java#L22

**Comment by joaquinz916** [comment]
Funcionalidad terminada, ticket cerrado.
